<div style="background-color:green;" class="toggle" id="46234b4d-cf77-427a-a56a-4cc8d8d30854">RUNNER_ON_OK 10.67.2.163</div><div style="display:none;" id="pad_46234b4d-cf77-427a-a56a-4cc8d8d30854">{<br/>    "started": 1, <br/>    "invocation": {<br/>        "module_name": "ping", <br/>        "module_args": ""<br/>    }, <br/>    "results_file": "/root/.ansible_async/567660021782.4703", <br/>    "ansible_job_id": "567660021782.4703"<br/>}</div><br/>
<div style="background-color:red;" class="toggle" id="1001fd63-a38e-4f36-bb72-8f539ad2ee1a">RUNNER_ON_FAILED 10.67.2.163</div><div style="display:none;" id="pad_1001fd63-a38e-4f36-bb72-8f539ad2ee1a">{<br/>    "invocation": {<br/>        "module_name": "script", <br/>        "module_args": "/etc/ansible/_zKLNC"<br/>    }, <br/>    "stdout": "/usr/local/bin/pip\r\npip exists\r\n/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.\r\n  InsecurePlatformWarning\r\nRequirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages\r\nvirtualenv exists\r\nRequirement already up-to-date: pip in ./.virtualenvs/choi_wan/lib/python2.7/site-packages\r\ncheckout the choi_wan egg codes\r\nrm the /tmp/choi_wan\r\n\u001b[31mCannot uninstall requirement choi-wan, not installed\u001b[0m\r\nsvn: OPTIONS of 'https://svn.lab.intra.nsfocus.com/svn/espp/ncelery/choi-wan/worker': Server certificate verification failed: certificate issued for a different hostname, issuer is not trusted (https://svn.lab.intra.nsfocus.com)\r\nsvn: OPTIONS of 'https://192.168.5.246/svn/espp/ncelery/choi-wan/worker': Server certificate verification failed: certificate issued for a different hostname, issuer is not trusted (https://192.168.5.246)\r\npython: can't open file './setup.py': [Errno 2] No such file or directory\r\ninstalled python package list:\r\npip (7.1.0)\r\nsetuptools (18.0.1)\r\nwheel (0.24.0)\r\n/root/.ansible/tmp/ansible-tmp-1436795767.78-113187847334821/_zKLNC: line 71: wizard.py: command not found\r\n", <br/>    "changed": true, <br/>    "stderr": "OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug1: mux_client_request_session: master session id: 2\r\nShared connection to 10.67.2.163 closed.\r\n", <br/>    "rc": 127<br/>}</div><br/>
